const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('bula', {
  onFocusChat:callback=>ipcRenderer.on('bula:focus-chat',()=>callback()),
  history:()=>ipcRenderer.invoke('bula:history'),
  clearHistory:()=>ipcRenderer.invoke('bula:clear-history'),
  settings: () => ipcRenderer.invoke('bula:settings'),
  providers: () => ipcRenderer.invoke('bula:providers'),
  files:()=>ipcRenderer.invoke('bula:files'),
  wardrobe: () => ipcRenderer.invoke('bula:wardrobe'),
  catalog: () => ipcRenderer.invoke('bula:catalog'),
  state: () => ipcRenderer.invoke('bula:state'),
  select: value => ipcRenderer.invoke('bula:select', value),
  onState: callback => ipcRenderer.on('bula:state', (_event, state) => callback(state)),
  saveSettings: data => ipcRenderer.invoke('bula:save-settings', data),
  // the interface language ('auto' or zh-Hant / zh-Hans / en / ja); applies at once in every window
  uiLanguage: value => ipcRenderer.invoke('bula:ui-language', value),
  models: () => ipcRenderer.invoke('bula:models'),
  chat: (history, options) => ipcRenderer.invoke('bula:chat', history, options),
  openOutput:id=>ipcRenderer.invoke('bula:open-output',id),
  task: data => ipcRenderer.invoke('bula:task',data),
  onTask:callback=>{ipcRenderer.on('bula:task-event',(_event,data)=>callback(data));},
  taskSteer:data=>ipcRenderer.invoke('bula:task-steer',data),
  // 開發夥伴: attach to an existing Claude Code / Codex session (dev-companion.cjs)
  devState:()=>ipcRenderer.invoke('bula:dev-state'),
  devSessions:()=>ipcRenderer.invoke('bula:dev-sessions'),
  devAttach:data=>ipcRenderer.invoke('bula:dev-attach',data),
  devInput:text=>ipcRenderer.invoke('bula:dev-input',text),
  devAnswer:(requestId,allow)=>ipcRenderer.invoke('bula:dev-answer',requestId,allow),
  devInterrupt:()=>ipcRenderer.invoke('bula:dev-interrupt'),
  devLeave:()=>ipcRenderer.invoke('bula:dev-leave'),
  devDismiss:()=>ipcRenderer.invoke('bula:dev-dismiss'),
  onDev:callback=>ipcRenderer.on('bula:dev',(_event,data)=>callback(data)),
  operationPermissions:kind=>ipcRenderer.invoke('bula:operation-permissions',kind),
  computerSupport:()=>ipcRenderer.invoke('bula:computer-support'),
  officialSetup:()=>ipcRenderer.invoke('bula:official-setup'),
  emergencyStop:()=>ipcRenderer.invoke('bula:emergency-stop'),
  agentConsole:()=>ipcRenderer.invoke('bula:agent-console'),
  speak: text => ipcRenderer.invoke('bula:speak', text),
  stop: () => ipcRenderer.invoke('bula:stop'),
  mute: on => ipcRenderer.invoke('bula:mute', on),
  onMuted: callback => ipcRenderer.on('bula:muted', (_event, value) => callback(value)),
  compact: on => ipcRenderer.invoke('bula:compact',on),
  scale: value => ipcRenderer.invoke('bula:scale', value),
  chatSize: size => ipcRenderer.invoke('bula:chat-size', size),
  drag: phase => ipcRenderer.invoke('bula:drag', phase),
  modAsset: (modId, file) => ipcRenderer.invoke('bula:mod-asset', modId, file),
  live2dCore: () => ipcRenderer.invoke('bula:live2d-core'),
  installLive2dCore: () => ipcRenderer.invoke('bula:live2d-core-install'),
  voiceStatus: () => ipcRenderer.invoke('bula:voice-status'),
  setOpenAIKey: key => ipcRenderer.invoke('bula:set-openai-key', key),
  clearOpenAIKey: () => ipcRenderer.invoke('bula:clear-openai-key'),
  previewVoice: data => ipcRenderer.invoke('bula:preview-voice', data),
  openOpenAI: page => ipcRenderer.invoke('bula:open-openai', page),
  installKokoro: () => ipcRenderer.invoke('bula:kokoro-install'),
  // voice profiles (voice-service.cjs); 錄音複製 opens the 聲音工作室 window (voice-lab.cjs)
  openVoiceLab: () => ipcRenderer.invoke('bula:open-voice-lab'),
  voices: () => ipcRenderer.invoke('bula:voices'),
  voiceSave: data => ipcRenderer.invoke('bula:voice-save', data),
  voicePreview: data => ipcRenderer.invoke('bula:voice-preview', data),
  voiceBind: id => ipcRenderer.invoke('bula:voice-bind', id),
  voiceSpeed: (id, speed, quality) => ipcRenderer.invoke('bula:voice-speed', id, speed, quality),
  voiceRemove: id => ipcRenderer.invoke('bula:voice-remove', id),
  voicePolicy: id => ipcRenderer.invoke('bula:voice-policy', id),
  voiceExport: id => ipcRenderer.invoke('bula:voice-export', id),
  voiceImport: () => ipcRenderer.invoke('bula:voice-import'),
  voiceJapanese: () => ipcRenderer.invoke('bula:voice-japanese'),
  voicevoxStatus: () => ipcRenderer.invoke('bula:voicevox-status'),
  voicevoxSpeakers: () => ipcRenderer.invoke('bula:voicevox-speakers'),
  installVoicevox: () => ipcRenderer.invoke('bula:voicevox-install'),
  onVoicevoxProgress: callback => ipcRenderer.on('bula:voicevox-progress', (_event, value) => callback(value)),
  openGame: (engine, game) => ipcRenderer.invoke('bula:open-game', engine, game),
  personOpen: () => ipcRenderer.invoke('bula:person-open'),
  personList: () => ipcRenderer.invoke('bula:person-list'),
  personEdit: id => ipcRenderer.invoke('bula:person-edit', id),
  personDelete: id => ipcRenderer.invoke('bula:person-delete', id),
  remoteStatus: () => ipcRenderer.invoke('bula:remote-status'),
  remoteEnable: () => ipcRenderer.invoke('bula:remote-enable'),
  remoteDisable: () => ipcRenderer.invoke('bula:remote-disable'),
  remotePair: () => ipcRenderer.invoke('bula:remote-pair'),
  remoteRevoke: id => ipcRenderer.invoke('bula:remote-revoke', id),
  remoteTasks: allow => ipcRenderer.invoke('bula:remote-tasks', allow),
  onSettingsChanged: callback => ipcRenderer.on('bula:settings-changed', (_event, value) => callback(value)),
  onRemoteChat: callback => ipcRenderer.on('bula:remote-chat', (_event, value) => callback(value)),
  watchSources: () => ipcRenderer.invoke('bula:watch-sources'),
  watchStart: data => ipcRenderer.invoke('bula:watch-start', data),
  watchStop: () => ipcRenderer.invoke('bula:watch-stop'),
  onWatch: callback => ipcRenderer.on('bula:watch', (_event, value) => callback(value)),
  gameEngines: () => ipcRenderer.invoke('bula:game-engines'),
  setJevKey: key => ipcRenderer.invoke('bula:set-jev-key', key),
  clearJevKey: () => ipcRenderer.invoke('bula:clear-jev-key'),
  openJevKeys: () => ipcRenderer.invoke('bula:open-jev-keys'),
  cliStatus: () => ipcRenderer.invoke('bula:cli-status'),
  setupCli: name => ipcRenderer.invoke('bula:cli-setup', name),
  llmStatus: () => ipcRenderer.invoke('bula:llm-status'),
  installLlm: id => ipcRenderer.invoke('bula:llm-install', id),
  removeLlm: id => ipcRenderer.invoke('bula:llm-remove', id),
  onLlmProgress: callback => ipcRenderer.on('bula:llm-progress', (_event, value) => callback(value)),
  micAudio: samples => ipcRenderer.send('bula:mic', samples),
  setOnboarded: () => ipcRenderer.invoke('bula:onboarded'),
  wakeStatus: () => ipcRenderer.invoke('bula:wake-status'),
  wakeSettings: data => ipcRenderer.invoke('bula:wake-settings', data),
  installAsr: () => ipcRenderer.invoke('bula:asr-install'),
  onAsrProgress: callback => ipcRenderer.on('bula:asr-progress', (_event, value) => callback(value)),
  onWake: callback => ipcRenderer.on('bula:wake', (_event, value) => callback(value)),
  onMicLevel: callback => ipcRenderer.on('bula:mic-level', (_event, value) => callback(value)),
  onDictation: callback => ipcRenderer.on('bula:dictation', (_event, value) => callback(value)),
  listenCancel: () => ipcRenderer.invoke('bula:listen-cancel'),
  onBargeIn: callback => ipcRenderer.on('bula:barge-in', (_event, value) => callback(value)),
  onFollow: callback => ipcRenderer.on('bula:follow', (_event, value) => callback(value)),
  onTypeless: callback => ipcRenderer.on('bula:typeless', (_event, value) => callback(value)),
  onKokoroProgress: callback => ipcRenderer.on('bula:kokoro-progress', (_event, value) => callback(value)),
  cursor: () => ipcRenderer.invoke('bula:cursor'),
  stream: on => ipcRenderer.invoke('bula:stream', on),
  quit: () => ipcRenderer.invoke('bula:quit'),
  hide: () => ipcRenderer.invoke('bula:hide'),
  onSpeaking: callback => ipcRenderer.on('bula:speaking', (_event, on) => callback(on)),
  // spoken audio plays in this page (renderer.js); main waits for audioDone
  onAudioPlay: callback => ipcRenderer.on('bula:audio-play', (_event, clip) => callback(clip)),
  onAudioStop: callback => ipcRenderer.on('bula:audio-stop', (_event, id) => callback(id)),
  audioDone: (id, error) => ipcRenderer.invoke('bula:audio-done', id, error),
  platform: process.platform,
  // spoken audio plays in this page (renderer.js); main waits for audioDone
  onAudioPlay: callback => ipcRenderer.on('bula:audio-play', (_event, clip) => callback(clip)),
  onAudioStop: callback => ipcRenderer.on('bula:audio-stop', (_event, id) => callback(id)),
  audioDone: (id, error) => ipcRenderer.invoke('bula:audio-done', id, error),
  platform: process.platform,
  onStreaming: callback => ipcRenderer.on('bula:streaming', (_event, on) => callback(on)),
  onNotice: callback => ipcRenderer.on('bula:notice', (_event, text) => callback(text))
});
// the interface language for i18n.js: the dictionary once, synchronously, before the page renders; then every change
contextBridge.exposeInMainWorld('i18nBridge',{get:()=>ipcRenderer.sendSync('i18n:get'),onChange:callback=>ipcRenderer.on('i18n:changed',(_event,value)=>callback(value))});
